### ISSUE TITLE
瓦罗书剑龙是否应当为巨型

### ISSUE THREAD

**Issue by kywvane** [DND5eChm/DND5e_chm#2]
引用地址
https://github.com/DND5eChm/DND5e_chm/blob/main/%E7%93%A6%E7%BD%97%E6%80%AA%E7%89%A9%E6%8C%87%E5%8D%97/%E5%9B%BE%E9%89%B4/%E5%89%91%E9%BE%99.htm

原文
Huge beast, unaligned

**Comment by zeroxilo** [comment]
如果是文本纠错，请别丢github哦。
https://docs.qq.com/form/page/DRVV3WFFvbGJmcEVp
