### ISSUE TITLE
[常见问题解决方案]下载的CHM文件在win11打开为空白

### ISSUE THREAD

**Issue by hjkl950217** [DND5eChm/DND5e_chm#41]
下载后直接打开，左侧的目录能显示，但是点击后右侧为空白。

PS：也许下载专门的预览软件能打开，但是chm应该系统自带的就能查看。。必须使用专门软件的话不方便使用

可能是打包的问题，旧版的天麟版本能正常显示。

**Comment by kagangtuya-star** [comment]
打开会有一个关于安全的弹框，关闭它或者不点击信任就会空白。这是CHm的特性，你可以再下载一个新的重新打开试试

**Comment by hjkl950217** [comment]
没有这个弹窗哒

**Comment by hjkl950217** [comment]
找到解决办法了：右键点击chm文件，选择“属性”，在“常规”选项卡中找到“解除锁定”选项并勾选，然后重新打开文件

**Comment by kagangtuya-star** [comment]
经几个Win11用户测试后无法复现结果，请排查文件属性问题。
尝试如下操作:
1. 右键CHm文件，点击属性。
2. 点击“常规”选卡下的“解除锁定”按钮，点击应用并确定。
3. 重新打开CHm文件。

**Comment by kagangtuya-star** [comment]
看来已经解决了。

**Comment by hjkl950217** [comment]
恩 ，确实是这样。。之前的天鳞版能直接打开，我就没有怀疑到是系统上的问题。感谢
