### ISSUE TITLE
眼魔书的修整期-范例修整期活动中角斗的部分有误

### ISSUE THREAD

**Issue by shakugannosaints** [DND5eChm/DND5e_chm#8]
现有问题的内容如下：

角色必须进行三次检定：力量（运动），敏捷（杂技）以及一特殊的w|z定有著相于角色骰一次最大生命骰的加值(@次骰不花M那生命骰)。如果需要，角色可以用一次角色的武器的攻z定取代上述的其中一z定。

每次花在角Y上的休整期有10%C率引ly}，相P例子在角Yy}表上。

**Comment by zeroxilo** [comment]
译文纠错别丢Issue里，丢纠错表
